# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'SwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'LeanCloud', '17.6.1'
 
  target 'SwiftDemoTests' do
    inherit! :search_paths
  end

  target 'SwiftDemoUITests' do
    inherit! :search_paths
  end

end
