# Uncomment the next line to define a global platform for your project
platform :ios, ‘10.0’

target 'ChatDemo' do
pod 'AVOSCloud', '12.3.0'
pod 'AVOSCloudIM', '12.3.0'
#pod 'LeanCloudFeedback', '~> 0.1.3'
pod 'LeanCloudFeedback'
pod 'AFNetworking', '~> 3.1.0'
pod 'AVOSCloudLiveQuery', '12.3.0'
#pod 'WechatOpenSDK'

end
